development:
  adapter: postgresql
  database: my_first_app
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: my_first_app
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: my_first_app
  username: postgres
  password: postgres
  host: localhost